# Generated by Django 2.0.2 on 2018-03-05 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M33er',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[a-z]+$')])),
                ('arrival_date', models.DateField()),
                ('startup', models.CharField(choices=[('thfr', 'Theodo FR'), ('bam', 'BAM'), ('thuk', 'Theodo UK'), ('sic', 'Sicara'), ('sip', 'Sipios')], max_length=10)),
            ],
        ),
    ]
