# Generated by Django 2.0.2 on 2018-03-05 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m33er',
            name='alias',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]+$')]),
        ),
    ]
